from query5horizGroundTruth import matches as gt5
from oakland1GroundTruth import matches as oak
import pprint

for line in open('/home/ericl/gtt_override'):
    if line:
        k, v = line.strip().split(';')
        v = v[:-4]
        print k, v
        if '2011-04' in k:
            matches = gt5
        elif '2011-10-28' in k:
            matches = oak
        else:
            assert False, line
        if v not in matches[k]:
            matches[k].append(v)

with open('query5horizGroundTruth.py', 'w') as output:
    output.write('# generated by mergegt.py\n')
    output.write('matches = ')
    pprint.pprint(gt5, stream=output)

with open('oakland1GroundTruth.py', 'w') as output:
    output.write('# generated by mergegt.py\n')
    output.write('matches = ')
    pprint.pprint(oak, stream=output)

fail = {}
for line in open('/home/ericl/gtf_override'):
    if line:
        k, v = line.strip().split(';')
        v = v[:-4]
        if k not in fail:
            fail[k] = []
        fail[k].append(v)
with open('gtfail.py', 'w') as output:
    output.write('# KNOWN FAILURES by mergegt.py\n')
    output.write('matches = ')
    pprint.pprint(fail, stream=output)
